### ISSUE TITLE
v-bind with object of attributes is not supported

### ISSUE THREAD

**Issue by faceyspacey** [SmallComfort/react-vue-loader#5]
The following isn't supported yet:

```js
<!-- binding an object of attributes -->
<div v-bind="{ id: someProp, 'other-attr': otherProp }"></div>
```

**Comment by SmallComfort** [comment]
Hi!

This issue has been fixed in new version. The lastest react-vue-loader version is 0.0.7

Thanks for your issue.

**Comment by faceyspacey** [comment]
Awesome. thanks brother. Do you think u can publish my PR for react-vue to NPM: https://www.npmjs.com/package/react-vue

?

**Comment by SmallComfort** [comment]
Yes!
react-vue-helper lastest version 0.0.6
